# Generated by Django 3.0.4 on 2020-03-14 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='webiste_url',
            new_name='website_url',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('010-?[0-9]\\d{4}-?\\d{4}$')]),
        ),
    ]
